name: Release NuGet Package

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and Publish NuGet Package
      run: |
        cd Vandar/Vandar.Contracts
        dotnet clean
        dotnet restore
        dotnet build
        dotnet pack --configuration Release
        ls ./bin/Release/
        dotnet nuget push ./bin/Release/Vandar.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
      
