stages:
  - release

release:
  image: mcr.microsoft.com/dotnet/sdk:9.0
  stage: release
  rules:
    - if: '$CI_COMMIT_REF_NAME == "release"'
      changes: 
       - Vandar/Vandar.Core/**
  retry: 2
  script:
    - "cd Vandar"
    - "cd Vandar.Core"
    - "dotnet clean"
    - "dotnet restore"
    - "dotnet build"
    - "dotnet pack --configuration Release"
    - "ls ./bin/Release/"
    - "dotnet nuget push ./bin/Release/Vandar.Core.*.nupkg --source $servernuget --api-key $nugetkey"

release_AspNetCore:
  image: mcr.microsoft.com/dotnet/sdk:9.0
  stage: release
  tags:
    - registry
  rules:
    - if: '$CI_COMMIT_REF_NAME == "release"'
      changes: 
       - Vandar/Vandar.AspNetCore/**
  retry: 2
  script:
    - "cd Vandar"
    - "cd Vandar.AspNetCore"
    - "dotnet clean"
    - "dotnet build"
    - "dotnet pack --configuration Release"
    - "ls ./bin/Release/"
    - "dotnet nuget push ./bin/Release/Vandar.AspNetCore.*.nupkg --source $servernuget --api-key $nugetkey"
