name: Release NuGet Packages

on:
  push:
    branches:
      - release

jobs:
  release_vandar_core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Pack and Push VandarSharp.Core
        working-directory: VandarSharp.Core
        run: |
          dotnet clean
          dotnet restore
          dotnet build
          dotnet pack --configuration Release
          ls ./bin/Release/
          dotnet nuget push ./bin/Release/VandarSharp.Core.*.nupkg --source ${{ secrets.SERVER_NUGET }} --api-key ${{ secrets.NUGET_KEY }}

  release_vandar_aspnetcore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Pack and Push Vandar.AspNetCore
        working-directory: Vandar.AspNetCore
        run: |
          dotnet clean
          dotnet restore
          dotnet build
          dotnet pack --configuration Release
          ls ./bin/Release/
          dotnet nuget push ./bin/Release/Vandar.AspNetCore.*.nupkg --source ${{ secrets.SERVER_NUGET }} --api-key ${{ secrets.NUGET_KEY }}
